// TODO: Evertime we will write same thing three times, We need a helper method to make our life easy.... also for actionCreator
// Normal action only has one type, async action will have success and fail
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAIL = 'CREATE_TEMPLATE_FAIL';
export const CREATE_ANOTHER_TEMPLATE = 'CREATE_ANOTHER_TEMPLATE';

export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_FAIL = 'UPDATE_TEMPLATE_FAIL';

export const SHOW_UPDATE_TEMPLATE_MODAL = 'SHOW_UPDATE_TEMPLATE_MODAL';
export const SHOW_UPDATE_TEMPLATE_MODAL_SUCCESS = 'SHOW_UPDATE_TEMPLATE_MODAL_SUCCESS';
export const SHOW_UPDATE_TEMPLATE_MODAL_FAIL = 'SHOW_UPDATE_TEMPLATE_MODAL_FAIL';
export const CLOSE_UPDATE_TEMPLATE_MODAL = 'CLOSE_UPDATE_TEMPLATE_MODAL';

export const SHOW_TEMPLATE_MODAL = 'SHOW_TEMPLATE_MODAL';
export const SHOW_TEMPLATE_MODAL_SUCCESS = 'SHOW_TEMPLATE_MODAL_SUCCESS';
export const SHOW_TEMPLATE_MODAL_FAIL = 'SHOW_TEMPLATE_MODAL_FAIL';
export const CLOSE_TEMPLATE_MODAL = 'CLOSE_TEMPLATE_MODAL';

export const RESET_TEMPLATE_ID = 'RESET_TEMPLATE_ID';

export const SHOW_TEMPLATE_NAME_MODAL = 'SHOW_TEMPLATE_NAME_MODAL';
export const HIDE_TEMPLATE_NAME_MODAL = 'HIDE_TEMPLATE_NAME_MODAL';

export const SEND_TO_PURCHASERSOLICITOR = 'SEND_TO_PURCHASERSOLICITOR';
export const SEND_TO_PURCHASERSOLICITOR_SUCCESS = 'SEND_TO_PURCHASERSOLICITOR_SUCCESS';
export const SEND_TO_PURCHASERSOLICITOR_FAIL = 'SEND_TO_PURCHASERSOLICITOR_FAIL';

export const IMPORT_TEMPLATE = 'IMPORT_TEMPLATE';

// purhcaser solicitor
export const GET_PURCHASERSOLICITOR_DOCUMENT = 'GET_PURCHASERSOLICITOR_DOCUMENT';
export const GET_PURCHASERSOLICITOR_DOCUMENT_SUCCESS = 'GET_PURCHASERSOLICITOR_DOCUMENT_SUCCESS';
export const GET_PURCHASERSOLICITOR_DOCUMENT_FAIL = 'GET_PURCHASERSOLICITOR_DOCUMENT_FAIL';

export const PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION = 'PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION';
export const PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION_SUCCESS = 'PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION_SUCCESS';
export const PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION_FAIL = 'PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION_FAIL';

export const PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION = 'PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION';
export const PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION_SUCCESS = 'PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION_SUCCESS';
export const PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION_FAIL = 'PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION_FAIL';

export const PURCHASERSOLICITOR_FINISH_REVIEW = 'PURCHASERSOLICITOR_FINISH_REVIEW';
export const PURCHASERSOLICITOR_FINISH_REVIEW_SUCCESS = 'PURCHASERSOLICITOR_FINISH_REVIEW_SUCCESS';
export const PURCHASERSOLICITOR_FINISH_REVIEW_FAIL = 'PURCHASERSOLICITOR_FINISH_REVIEW_FAIL';

export const PURCHASERSOLICITOR_ACCEPT_REJECTION = 'PURCHASERSOLICITOR_ACCEPT_REJECTION';
export const PURCHASERSOLICITOR_ACCEPT_REJECTION_SUCCESS = 'PURCHASERSOLICITOR_ACCEPT_REJECTION_SUCCESS';
export const PURCHASERSOLICITOR_ACCEPT_REJECTION_FAIL = 'PURCHASERSOLICITOR_ACCEPT_REJECTION_FAIL';

// vendor solicitor
export const GET_VENDORSOLICITOR_DOCUMENT = 'GET_VENDORSOLICITOR_DOCUMENT';
export const GET_VENDORSOLICITOR_DOCUMENT_SUCCESS = 'GET_VENDORSOLICITOR_DOCUMENT_SUCCESS';
export const GET_VENDORSOLICITOR_DOCUMENT_FAIL = 'GET_VENDORSOLICITOR_DOCUMENT_FAIL';

export const VENDORSOLICITOR_COMPLETE_DOCUMENT = 'VENDORSOLICITOR_COMPLETE_DOCUMENT';
export const VENDORSOLICITOR_COMPLETE_DOCUMENT_SUCCESS = 'VENDORSOLICITOR_COMPLETE_DOCUMENT_SUCCESS';
export const VENDORSOLICITOR_COMPLETE_DOCUMENT_FAIL = 'VENDORSOLICITOR_COMPLETE_DOCUMENT_FAIL';

// document section
export const SOLICITOR_ACCEPT_SECTION = 'SOLICITOR_ACCEPT_SECTION';
export const SOLICITOR_ACCEPT_SECTION_SUCCESS = 'SOLICITOR_ACCEPT_SECTION_SUCCESS';
export const SOLICITOR_ACCEPT_SECTION_FAIL = 'SOLICITOR_ACCEPT_SECTION_FAIL';

export const SOLICITOR_REJECT_SECTION = 'SOLICITOR_REJECT_SECTION';
export const SOLICITOR_REJECT_SECTION_SUCCESS = 'SOLICITOR_REJECT_SECTION_SUCCESS';
export const SOLICITOR_REJECT_SECTION_FAIL = 'SOLICITOR_REJECT_SECTION_FAIL';

export const SOLICITOR_COUNTEROFFER_SECTION = 'SOLICITOR_COUNTEROFFER_SECTION';
export const SOLICITOR_COUNTEROFFER_SECTION_SUCCESS = 'SOLICITOR_COUNTEROFFER_SECTION_SUCCESS';
export const SOLICITOR_COUNTEROFFER_SECTION_FAIL = 'SOLICITOR_COUNTEROFFER_SECTION_FAIL';

export const SOLICITOR_UPDATE_SECTION = 'SOLICITOR_UPDATE_SECTION';
export const SOLICITOR_UPDATE_SECTION_SUCCESS = 'SOLICITOR_UPDATE_SECTION_SUCCESS';
export const SOLICITOR_UPDATE_SECTION_FAIL = 'SOLICITOR_UPDATE_SECTION_FAIL';

// export const SOLICITOR_EDITABLE_SECTION = 'SOLICITOR_EDITABLE_SECTION';
// export const DIFF_SECTION = 'DIFF_SECTION';
export const SOLICITOR_ADD_UNDONE_SECTION = 'SOLICITOR_ADD_UNDONE_SECTION';
export const SOLICITOR_REMOVE_UNDONE_SECTION = 'SOLICITOR_REMOVE_UNDONE_SECTION';

export const SAVE_COMMENT_AND_CHANGE_STATUS = 'SAVE_COMMENT_AND_CHANGE_STATUS';
export const SAVE_COMMENT_AND_CHANGE_STATUS_SUCCESS = 'SAVE_COMMENT_AND_CHANGE_STATUS_SUCCESS';
export const SAVE_COMMENT_AND_CHANGE_STATUS_FAIL = 'SAVE_COMMENT_AND_CHANGE_STATUS_FAIL';

export const SHOW_CONTRACT_VIEW_MODAL = 'SHOW_CONTRACT_VIEW_MODAL';
export const HIDE_CONTRACT_VIEW_MODAL = 'HIDE_CONTRACT_VIEW_MODAL';

export const SHOW_COMMENT_MODAL = 'SHOW_COMMENT_MODAL';
export const SHOW_COMMENT_MODAL_SUCCESS = 'SHOW_COMMENT_SUCCESS_MODAL';
export const SHOW_COMMENT_MODAL_FAIL = 'SHOW_COMMENT_FAIL_MODAL';

export const HIDE_COMMENT_MODAL = 'HIDE_COMMENT_MODAL';

export const SAVE_COMMENT = 'SAVE_COMMENT';
export const SAVE_COMMENT_SUCCESS = 'SAVE_COMMENT_SUCCESS';
export const SAVE_COMMENT_FAIL = 'SAVE_COMMENT_FAIL';

export const SHOW_USER_ACTIVITY_MODAL = 'SHOW_USER_ACTIVITY_MODAL';
export const SHOW_USER_ACTIVITY_MODAL_SUCCESS = 'SHOW_USER_ACTIVITY_MODAL_SUCCESS';
export const SHOW_USER_ACTIVITY_MODAL_FAIL = 'SHOW_USER_ACTIVITY_MODAL_FAIL';
export const HIDE_USER_ACTIVITY_MODAL = 'HIDE_USER_ACTIVITY_MODAL';


// for demo only
export const DEMO_NEW = 'DEMO_NEW';
export const DEMO_NEW_SUCCESS = 'DEMO_NEW_SUCCESS';
