
import * as ActionTypes from './actionTypes';
import createAction from 'utils/createAction';

export const getPurchaserSolicitorDocument = createAction(ActionTypes.GET_PURCHASERSOLICITOR_DOCUMENT);
export const getPurchaserSolicitorDocumentSuccess = createAction(ActionTypes.GET_PURCHASERSOLICITOR_DOCUMENT_SUCCESS);
export const getPurchaserSolicitorDocumentFail = createAction(ActionTypes.GET_PURCHASERSOLICITOR_DOCUMENT_FAIL);

export const purchaserSolicitorAcceptInitSP = createAction(ActionTypes.PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION);
export const purchaserSolicitorAcceptInitSPSuccess = createAction(ActionTypes.PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION_SUCCESS);
export const purchaserSolicitorAcceptInitSPFail = createAction(ActionTypes.PURCHASERSOLICITOR_ACCEPT_INITSPECIALCONDITION_FAIL);

export const purchaserSolicitorRejectInitSP = createAction(ActionTypes.PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION);
export const purchaserSolicitorRejectInitSPSuccess = createAction(ActionTypes.PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION_SUCCESS);
export const purchaserSolicitorRejectInitSPFail = createAction(ActionTypes.PURCHASERSOLICITOR_REJECT_INITSPECIALCONDITION_FAIL);

export const purchaserSolicitorFinishReview = createAction(ActionTypes.PURCHASERSOLICITOR_FINISH_REVIEW);
export const purchaserSolicitorFinishReviewSuccess = createAction(ActionTypes.PURCHASERSOLICITOR_FINISH_REVIEW_SUCCESS);
export const purchaserSolicitorFinishReviewFail = createAction(ActionTypes.PURCHASERSOLICITOR_FINISH_REVIEW_FAIL);

export const purchaserSolicitorAcceptRejection = createAction(ActionTypes.PURCHASERSOLICITOR_ACCEPT_REJECTION);
export const purchaserSolicitorAcceptRejectionSuccess = createAction(ActionTypes.PURCHASERSOLICITOR_ACCEPT_REJECTION_SUCCESS);
export const purchaserSolicitorAcceptRejectionFail = createAction(ActionTypes.PURCHASERSOLICITOR_ACCEPT_REJECTION_FAIL);
