
export const SEARCH_ALL_EVENT = 'SEARCH_ALL_EVENT';
export const GET_EVENT_LIST = 'GET_EVEMT_LIST';
export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const HIDE_EVENT_LIST_MODAL = 'HIDE_EVENT_LIST_MODAL';
export const HIDE_NEW_EVENT_MODAL = 'HIDE_NEW_EVENT_MODAL';
